### ISSUE TITLE
packages in environments.txt

### ISSUE THREAD

**Issue by lhaausing** [wala/graph4code#10]
Hi,

I have tried to install with requirements.txt but it turns out that a lot of the packages couldn't be installed due to the version problem (either version is not found with pip or there's some compatibility issues). I have questions listed below:

1. What would be the version of python3 that you are using? Could you share it?
2. Is it possible for you to list all package version that you're having? I guess it could be some problem when we don't have the full list of packages with their version.
3. Some dependencies are installed to extract the documentations. Is it possible for you guys to list out packages required for your code to work? For the extracting documentation part I can use the packages required for the dataset I'm dealing with.

Thanks a lot for answering in advance.

**Comment by ksrinivs64** [comment]
Can you try Python 3.7?  I believe thats what we used.  As for extracting the documentation, we ran into a lot of issues with the inspect API being quite unreliable, and ensuring that you use a virtual environment that has the module you have installed.  Other than that, there are no special requirements.

**Comment by Robin-Y-Ding** [comment]
I came across the same failure; I tried to use Python 3.7 to create a conda environment, but it turns out many packages could not be installed. Is there any way to fix this?

Thanks a lot.

**Comment by ibrahimabdelaziz** [comment]
can you please provide what list of packages are causing the error exactly? Also, are you installing the packages from https://github.com/wala/graph4code/blob/master/requirements.txt? All packages in this file have their versions provided!

**Comment by Robin-Y-Ding** [comment]
> can you please provide what list of packages are causing the error exactly? Also, are you installing the packages from https://github.com/wala/graph4code/blob/master/requirements.txt? All packages in this file have their versions provided!

Hi Ibrahim,

Thanks for your reply. Yeah, I am installing the packages from this requirement.txt by cloning the github repository and run:
```
conda create -n graph4code python=3.7; conda activate graph4code;
pip install -r requirements.txt
```
The first error I am getting is
```
ERROR: Could not find a version that satisfies the requirement intel-numpy==1.14.3 (from versions: 1.21.4)
ERROR: No matching distribution found for intel-numpy==1.14.3
```
Then I tried to install the latest version of intel-numpy since the error is saying the version is not available from pip. After this, I removed this line from the requirements.txt, and I get this second error:
```
ERROR: Could not find a version that satisfies the requirement mkl-fft==1.0.6 (from versions: 1.2.0, 1.3.0, 1.3.1)
ERROR: No matching distribution found for mkl-fft==1.0.6
```
I did the fix I mentioned above again to get over it. Then I got the following error:
```
ERROR: Could not find a version that satisfies the requirement torch==0.4.0 (from versions: 1.0.0, 1.0.1, 1.0.1.post2, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0)
ERROR: No matching distribution found for torch==0.4.0
```
Then I fixed it by installing the closest version (1.0.0), and finally I got this:
```
INFO: pip is looking at multiple versions of alabaster to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of absl-py to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement torch==0.4.0 (from allennlp) (from versions: 1.0.0, 1.0.1, 1.0.1.post2, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0)
ERROR: No matching distribution found for torch==0.4.0
```

**Comment by ksrinivs64** [comment]
I am able to reproduce the error - if you simply create a conda environment with 3.9 (or 3.7) one of the packages deep fails.  However, the best option going forward might be to simply create the conda environment like so:
`conda create --name g4c python=3.9`
`pip install bs4`
`pip install elasticsearch`
With that I was able to for instance run `generate_top_modules.py`.  If you are trying to run something else, please let me know and I will provide instructions.

**Comment by ksrinivs64** [comment]
I should mention we only test with Ubuntu.

**Comment by Robin-Y-Ding** [comment]
Hi @ksrinivs64,

I am actually using Ubuntu 20.04, but I still came across these package issues. Following your suggestion, I am able to run `generate_top_modules.py`, but with these specified packages, when I move forward, there is another version incompatibility coming out from elasticsearch (8.2.0 v.s. 7.0.4), and I might have to check back the versions indicated in the `requirements.txt` to make it work. I am assuming the same issue will come back again in other scripts and it might not be doable if I have to check every script to install the packages manually.

Could you please give some instructions to successfully install all the dependencies with `requirements.txt`?

Greatly appreciate your help!

**Comment by ksrinivs64** [comment]
Working on this - but will take a bit of time because ElasticSearch has changed how one connects to it, and we are updating everything to make it a bit simpler.  I should have this simplified in a week.

**Comment by ksrinivs64** [comment]
I've upgraded all the requirements for docstring extraction and storage to ElasticSearch 8.2.1., Python 3.9.  Please let me know if you have problems in this part.

**Comment by ibrahimabdelaziz** [comment]
@Robin-Y-Ding the README is now updated with step-by-step examples for each part of the pipeline. No need for the requirements file now, we just need very few libraries that are mentioned in the README file.

**Comment by lhaausing** [comment]
Sorry for the late reply and thanks a lot for updating. It's been working well for me so far!

**Comment by ksrinivs64** [comment]
No worries thanks for letting us know!
