### ISSUE TITLE
Issue in tasks 3-4 "collecting docstrings documentation" for scripts that contain built-in modules

### ISSUE THREAD

**Issue by maltesewalter** [wala/graph4code#12]
I am trying to create/collect a series of git repositories containing multiple python scripts.

Though, there is a problem in one of your scripts when I have to collect the docstrings documentations (to be run in the dir containing all analysis output previously collected): if one of the candidate python scripts chosen contains a built-in module like __future__ / functools, unittest, the script /src/inspect_docstrings_per_module.py (called inside scripts/inspect_modules_for_docstrings.sh) returns errors (as shown below) and the docstrings output for those modules (present in the top modules to inspect) is not created correctly.

The problem therefore seems to be related to the script to be run at step 3 (src/generate_top_modules.py) that shouldn’t consider these built-in modules to be installed (with pip install) within the conda environment creation done at step 4.
(I am referring to the steps at your GitHub page: https://github.com/wala/graph4code)

Right now I cannot proceed using custom GitHub repositories to be analysed because those always contain python scripts that include some built-in modules that results in this error at step 4 (after being selected as a top_module into /output/top_modules.json at step 3).

<img width="1440" alt="Screenshot 2022-08-10 at 12 37 02" src="https://user-images.githubusercontent.com/62718870/188920456-2c456ba2-8dde-4746-bb2a-fccd6fce777d.png">
<img width="1440" alt="Screenshot 2022-08-10 at 12 37 32" src="https://user-images.githubusercontent.com/62718870/188920486-a460f2c9-8730-4042-91b8-c498b50f97e8.png">

**Comment by maltesewalter** [comment]
linked to this problem (of the packages inside the "analysis_modules" in generate_top_modules.py), there is also the issue that not every package work with the forum graph creation.
Ex: when the python scripts that we want to analyse use matploplib or numpy as "top_modules", it doesn't work (0 triples found), while sci-kit learn does.
<img width="1440" alt="Screenshot 2022-09-26 at 15 45 16" src="https://user-images.githubusercontent.com/62718870/194028675-1936762e-3bd5-44e8-a4ea-8935e36ea44b.png">
<img width="1440" alt="Screenshot 2022-09-26 at 13 19 45" src="https://user-images.githubusercontent.com/62718870/194028753-ab6033bd-5c95-447e-8475-b1518a7085cc.png">
<img width="1440" alt="Screenshot 2022-09-26 at 18 13 04" src="https://user-images.githubusercontent.com/62718870/194029152-1e21fc9d-7775-48b0-9477-a7d4a58e61bd.png">

**Comment by ksrinivs64** [comment]
We did notice that depending on OS/Python versions etc, some modules could be inspected by Python successfully and others couldn't.  Our approach was to switch machines/Pythons etc to do it. It is annoying for sure, but unclear how to get around the problem - this is a Python problem.
