### ISSUE TITLE
macOS --arch64 laptop not compatible 

### ISSUE THREAD

**Issue by vipulpandey12345** [wala/graph4code#15]
Hi, here are the details for my mac: Chip: Mac M1 Pro. I have been trying to install compatible versions for elastic search but nothing is working. Can you tell give me the link for which version I need to install as well as what steps I need to follow to ensure elastic search will work on my device. Is there anything in the graph4code steps that I need to do different apart what is listed? Please and let me know! Thanks

**Comment by ksrinivs64** [comment]
Hi, can you try the instructions here: https://github.com/wala/graph4code/tree/master/semForms - these use docker so you should be insulated a bit more from OS issues.
