### ISSUE TITLE
help and next steps...

### ISSUE THREAD

**Issue by beejaya** [wala/graph4code#16]
I have a question/issue: I am trying to follow the process specified here on example_scripts/test1.py. Ignoring some errors I am getting during the steps, I am reasonably successful in running the steps upto and including "Creating dosctrings graph."

1. When I look at the example triplet {example1.py, example1.json, example1.nq} in the sample_graph directory with what I get for test1.py, the docstrings_triples.nq file I have is much larger than the example1.nq: about 300,000 lines vs. 615 lines. I would appreciate an expalanation of why and recommendation on how to "fix" it. What was done for creating example1.nq vs. docstrings_triples.nq file I am getting?
2. Using example1.nq as the example, is it possible to share an outline and queries of what comes next: loading that nq file into a db and example queries on this graph that could be of interest just to kick-start some possibilities?

**Comment by ibrahimabdelaziz** [comment]
Hello, 
Regarding 1, I'm not sure I understand the source of your problem. Can you possibly share that file `example1.nq`, it might help us understand what's going on.
Regarding 2, please check https://dl.acm.org/doi/10.1145/3460210.3493578 and https://wala.github.io/graph4code/example_queries.html  for some example queries.

**Comment by beejaya** [comment]
Hi @ibrahimabdelaziz thanks for the response. Just to be clear, example1.nq that I referred to is as it is given in the sample_graph folder in this repo. I didn't touch or create it. I am just comparing it to the nq file I get on example_scripts/test1.py by following the steps up to "creating docstrings graph". Here is nq file that I got split into two parts due to upload size limitations:
[docstrings_triples_part1.zip](https://github.com/wala/graph4code/files/11011829/docstrings_triples_part1.zip)
[docstrings_triples_part2.zip](https://github.com/wala/graph4code/files/11011830/docstrings_triples_part2.zip)

I will take a look at the other links for the 2nd question. Appreciate your help.

**Comment by beejaya** [comment]
@ibrahimabdelaziz while I wait for your help on the above, I started looking at the 2nd question. I thought I would start with what is already in the repo: the nq files at https://github.com/wala/graph4code/tree/master/sample_graph and the queries at https://github.com/wala/graph4code/tree/master/usage_queries. I am able to load and see the nq files data in my Jena Fuseki instance. But I am having difficulty running any of the sparql queries on any of nq files. Is there a consistent set of one nq file and some example queries that go with that which you can share which would work out of the box? Thanks.

**Comment by ksrinivs64** [comment]
I think a lot of those existing examples and nq are outdated.  At some point we switched to working primarily on the JSON representation of the output just because it was hard to express edge properties with SPARQL and we needed edge properties on the edges of the graph a lot.  I added samples from test1.py into output/static_analysis as shown in the instructions.  Let me know if that helps?
