### ISSUE TITLE
Built-in modules and modules with aliases have issues generating docstring knowledge graphs?

### ISSUE THREAD

**Issue by a825335172** [wala/graph4code#18]
I am very grateful for taking the time to answer my questions amidst your busy schedule. I have encountered some issues again. When I generate the knowledge graph of the docstring, I find that the built-in modules such as inspect cannot generate its knowledge graph normally because pip cannot download the built-in modules. For some modules with aliases such as sklearn, the version downloaded by pip is also sklearn instead of sklearn-stick, which causes problems in generating the knowledge graph. However, the import sklearn in the sample you provided can generate the knowledge graph normally.

**Comment by a825335172** [comment]
I discovered that modules  with aliases, I can successfully generate a knowledge graph as long as I download them in my environment. However, built-in modules still don't work, such as the inspect and os modules.

**Comment by ksrinivs64** [comment]
Hi thanks for your interest in our project!  The issues with inspect and not being able to inspect certain modules are unfortunately beyond the scope of our code - these are Python inspection issues, and am afraid we cannot solve the problem - we have noticed wide variance in success based on OS/version of module/version of Python etc.

**Comment by clarismiranda** [comment]
Hello, 

I was wondering if you have made available the Python script `../get_base_module`; this is for the script [inspect_std_libs_for_docstrings.sh](https://github.com/wala/graph4code/blob/master/scripts/inspect_std_libs_for_docstrings.sh).

Or how can I inspect standard/built-in libraries?
