### ISSUE TITLE
How to update graph4code with latest data?

### ISSUE THREAD

**Issue by smith-co** [wala/graph4code#19]
I'm quite curious and interested in understanding how to keep graph4code up-to-date with the latest data.  Could you possibly elaborate on the steps or procedures involved in updating graph4code? Also, is it possible to automate this update process to ensure that the latest data is always incorporated into graph4code in an ongoing basis?

**Comment by ksrinivs64** [comment]
Hi, graph4code is really a tool - you can run it as many times as you want on some new dataset.  Just set up a cron job to run it the way its described perhaps?
