### ISSUE TITLE
CodeBreakerPrereq-0.0.1-SNAPSHOT.jar not exists 

### ISSUE THREAD

**Issue by yaoyh116** [wala/graph4code#21]
When I execute ‘bash setup.sh’ to build the code analysis library, there exists an error "Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.4:install-file (default-cli) on project standalone-pom: The specified file '/workspace/graph4code-master/code_breaker_prereq/target/CodeBreakerPrereq-0.0.1-SNAPSHOT.jar' not exists". And I can't find the jar file.May I ask how to deal with it? Thank u!

**Comment by TsukimiRini** [comment]
Same problem

**Comment by juliandolby** [comment]
Sorry, some confusion uploading files.  For now, the jar files are available at https://archive.org/download/graph4code_prereq_jars/graph4code_prereq_jars.tar.  Download that file, and untar it in the root directory of your graph4code clone.

**Comment by hwgobs** [comment]
https://archive.org/download/graph4code_prereq_jars/graph4code_prereq_jars.tar

This link is not available.
