### ISSUE TITLE
Does WALA support Python?

### ISSUE THREAD

**Issue by v587su** [wala/graph4code#7]
You mentioned in the paper that WALA can analyze Python source code, but I can't find python support in WALA's README. How can I use WALA for analysing Python source code?

**Comment by ksrinivs64** [comment]
Will have this done by end of week.

**Comment by ksrinivs64** [comment]
I've updated the instructions in the main readme for how to use WALA on Python scripts to do your own analysis.  Please give it a try and let me know if you have issues.

**Comment by v587su** [comment]
> I've updated the instructions in the main readme for how to use WALA on Python scripts to do your own analysis. Please give it a try and let me know if you have issues.

Thanks. It works. Really appreciate your work.
