### ISSUE TITLE
Error: Could not find or load main class util.RunTurtleSingleAnalysis

### ISSUE THREAD

**Issue by nali001** [wala/graph4code#9]
@ksrinivs64 
When I try to run the code analysis part using: 
`java -DoutputDir=hello.json -cp codebreaker3.jar util.RunTurtleSingleAnalysis hello.py null null `

I got the error: 
```
Error: Could not find or load main class util.RunTurtleSingleAnalysis
Caused by: java.lang.ClassNotFoundException: util.RunTurtleSingleAnalysis
```

Could you help me with it?

**Comment by ibrahimabdelaziz** [comment]
Hi,
Can you please confirm that you are running the above command from the jars directory? Also, sometimes git LFS does not download these large files properly. Can you please verify the size of the jar you are running, with `ls -l` or so ?

**Comment by nali001** [comment]
Problem solved. It turned out to be that I didn't download the proper codebreaker3.jar file. Thanks so much!
